#DROP TABLE IF EXISTS urls;
#DROP TABLE IF EXISTS url_checks;
CREATE TABLE urls (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE url_checks (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    url_id BIGINT NOT NULL,
    status_code INT NULL,
    h1 VARCHAR(255) NULL,
    title TEXT NULL,
    description TEXT NULL,
    created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);