    <?php echo $this->fetch("header.phtml");?>

    <?php if($successMes): ?>
    <div class="alert alert-success" role="alert"><?=$successMes;?></div>
    <?php endif ?>

    <?php if($errorMes) : ?>
    <div class="alert alert-danger" role="alert"><?php echo $errorMes;?></div>
    <?php endif ?>

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: </h1>
                <div class="table-responsive">
                    <table class="table table-bordered table-hover text-nowrap" data-test="url">
                        <tbody>
                            <tr>
                                <td>ID</td>
                                <td><?=$id?></td>
                            </tr>
                            <tr>
                                <td>Имя</td>
                                <td><?=$name?></td>
                            </tr>
                            <tr>
                                <td>Дата создания</td>
                                <td><?=$createdAt?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            <h2 class="mt-5 mb-3">Проверки</h2>
            <form method="post" action="/urls/<?=$id?>/checks">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
                </thead>
                <tbody>
                    <?php foreach ($checks as $check): ?>
                    <tr>
                        <td><?=$check["id"]?></td>
                        <td><?php echo $check["status_code"]?></td>
                        <td><?php echo $check["h1"]?></td>
                        <td><?php echo $check["title"]?></td>
                        <td><?php echo $check["description"]?></td>
                        <td><?php echo $check["created_at"]?></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </main>
    <?php echo $this->fetch("footer.phtml");?>
