
    <?=$this->fetch("header.phtml");?>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайты</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Последняя проверка</th>
                            <th>Код ответа</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(count($urls) > 0): ?>
                            <?php foreach ($urls as $url): ?>
                                <tr>
                                    <td><?=$url['id']?></td>
                                    <td><?php echo $url['name']?></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            <?php endforeach ?>
                        <?php endif ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>
    <?=$this->fetch("footer.phtml");?>
