
    <?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
?>

    <?=$this->fetch("header.phtml");?>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайты</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Последняя проверка</th>
                            <th>Код ответа</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(count($urls) > 0): ?>
                            <?php foreach ($urls as $url): ?>
                                <tr>
                                    <td><?=$url['id']?></td>
                                    <td><a href="urls/<?=$url['id']?>"><?=$url['name']?></a></td>
                                    <td><? isset($url['check']) ? $url['check']['created_at'] : ""?></td>
                                    <td><?=isset($url['check']) ? $url['check']['status_code'] : ""?></td>
                                </tr>
                            <?php endforeach ?>
                        <?php endif ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>
    <?=$this->fetch("footer.phtml");?>
